info:
  app:
    name: catalog-reference-service
    description: reference

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 8101

catalog-reference-service:
  urnbase: http://urn.nb.no/

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
    profiles: docker

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/